version: "2"
services:

  postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow
    volumes:
    - postgres-db-volume:/data/postgres

  airflow:
    image: tumtumbear/airflow
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    - postgres
    environment:
    - LOAD_EX=n
    - EXECUTOR=Local
    volumes:
    - /Users/commanderdata/projects/auctionhunter/:/usr/local/airflow/dags
    networks:
    - airflow_mysql_net

  mongo:
    image: mongo
    ports:
    - "27018:27017"
    volumes:
    - db-data:/data/db
    - mongo-config:/data/configdb

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Cgeek898"
      MYSQL_DATABASE: "ebay"
    volumes:
    - mysql_data:/var/lib/mysql
    restart: always
    networks:
    - airflow_mysql_net

volumes:
  db-data:
  mongo-config:
  mysql_data:
  postgres-db-volume:

networks:
  airflow_mysql_net:
    driver: bridge