version: "2"
services:

  postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow

  airflow:
    image: tumtumbear/airflow
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    - postgres
    environment:
    - LOAD_EX=n
    - EXECUTOR=Local
    volumes:
    - /Users/commanderdata/projects/auctionhunter/:/usr/local/airflow/dags
  mongo:
    image: mongo
    ports:
    - "27018:27017"
    volumes:
    - db-data:/data/db
    - mongo-config:/data/configdb
volumes:
  db-data:
  mongo-config:
